---
# [ Install Dracut to Load ZFS ]###############################################
- name: Install Dracut to Load ZFS Block
  when:
    - ansible_nodename != "localhost"
  tags:
    - install_dracut
  block:
    - name: Run chroot command to install dracut # noqa Ansible [YAML]
      ansible.builtin.command:
        cmd: "{{ chroot_cmd }} bash -c '{{ item }}'"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      with_items:
        - "apt-get install --yes dracut-core zfs-dracut bsdmainutils bsdextrautils gcc"
        - "apt-mark hold {{ packages_to_mark_hold | join(' ') }}"
      when:
        - ansible_os_family == "Debian"

    - name: Copy dracut template to /mnt/etc/dracut.conf.d/100-zol.conf
      ansible.builtin.template:
        src: dracut_100-zol.conf.j2
        dest: "{{ live_cd_mountpoint }}/etc/dracut.conf.d/100-zol.conf"
        owner: "root"
        group: "root"
        mode: "0644"

    # Fix zfs dracut - https://github.com/openzfs/zfs/issues/13398
    # Need gcc to get libgcc_s.so for dracut_install to work
    - name: Fix "/**/" to "/*/*/" within /usr/lib/dracut/modules.d/90zfs/module-setup.sh
      ansible.builtin.replace:
        path: "{{ live_cd_mountpoint }}/usr/lib/dracut/modules.d/90zfs/module-setup.sh"
        regexp: '\/\*\*\/'
        replace: '/*/*/'

# Fix zfs bootfs systemd services
# https://github.com/openzfs/zfs/pull/13585/files
# https://github.com/openzfs/zfs/issues/14475
# /usr/lib/dracut/modules.d/90zfs/zfs-rollback-bootfs.service
# /usr/lib/dracut/modules.d/90zfs/zfs-snapshot-bootfs.service
    - name: Fix zfs bootfs systemd services ExecStart
      ansible.builtin.replace:
        path: "{{ live_cd_mountpoint }}/usr/lib/dracut/modules.d/90zfs/{{ item }}"
        regexp: '^-ExecStart=(.*$)'
        replace: 'ExecStart=\1'
      with_items:
        - "zfs-snapshot-bootfs.service"
        - "zfs-rollback-bootfs.service"

    - name: Fix zfs bootfs systemd services Semicolon
      ansible.builtin.replace:
        path: "{{ live_cd_mountpoint }}/usr/lib/dracut/modules.d/90zfs/{{ item }}"
        regexp: '^(.*)BOOTFS" SNAPNAME(.*$)'
        replace: '\1BOOTFS"; SNAPNAME\2'
      with_items:
        - "zfs-snapshot-bootfs.service"
        - "zfs-rollback-bootfs.service"

    - name: Create /etc/cmdline.d directory
      ansible.builtin.file:
        path: "/etc/cmdline.d"
        mode: "0755"
        state: directory

    - name: Configure Dracut Network without Dropbear
      ansible.builtin.lineinfile:
        path: "{{ live_cd_mountpoint }}/etc/dracut.conf.d/network.conf"
        line: 'install_items+=" /etc/cmdline.d/dracut-network.conf "'
        create: true
        mode: "0644"
        state: present
        backup: true
      when:
        - not enable_dropbear_support | default(false) | bool

    # [ Setup Dracut Networking without Dropbear ]#############################

    # With rd.neednet=1 it will fail to boot if no network available
    # This can be a problem with laptops and docking stations, if the dock
    # is not connected (no ethernet) it can fail to boot. Setting to 1 really
    # only needed with for Dropbear support
    - name: Create file /etc/cmdline.d/dracut-network.conf for DHCP
      ansible.builtin.lineinfile:
        path: "/etc/cmdline.d/dracut-network.conf"
        regexp: '(^.*ip=.*$)'
        line: 'ip={{ apply_dropbear_settings.remoteaccess_ip_config }} rd.neednet=0'
        create: true
        mode: "0644"
        state: present
        backup: true
      when:
        - not apply_dropbear_settings.remoteaccess_ip_config == "static"
        - not enable_dropbear_support | default(false) | bool

    # With rd.neednet=1 it will fail to boot if no network available
    # This can be a problem with laptops and docking stations, if the dock
    # is not connected (no ethernet) it can fail to boot. Setting to 1 really
    # only needed with for Dropbear support
    - name: Create file /etc/cmdline.d/dracut-network.conf for Static IP
      ansible.builtin.lineinfile:
        path: "/etc/cmdline.d/dracut-network.conf"
        regexp: '(^.*ip=.*$)'
        line: 'ip={{ apply_dropbear_settings.remoteaccess_ip }}:::{{ apply_dropbear_settings.remoteaccess_netmask }}:::none rd.neednet=0 rd.break'
        create: true
        mode: "0644"
        state: present
        backup: true
      when:
        - apply_dropbear_settings.remoteaccess_ip_config == "static"
        - not enable_dropbear_support | default(false) | bool
