---
# [ Install Syslinux Boot Loader ]##############################################
- name: Install Syslinux Boot Loader Block
  when:
    - ansible_nodename != "localhost"
  tags:
    - install_syslinux
  block:
    - name: Run chroot command to install Syslinux Boot Loader
      ansible.builtin.command:
        cmd: "{{ chroot_cmd }} bash -c '{{ item }}'"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      with_items:
        - "mkdir -p {{ syslinx_path }}"
        - "apt-get install --yes syslinux syslinux-common extlinux dosfstools unzip"
        - "cp -r /usr/lib/syslinux/modules/bios/* {{ syslinx_path }}"
        # Install extlinux
        - "extlinux --install {{ syslinx_path }}"
      when:
        - ansible_os_family == "Debian"

    - name: Run chroot command to install the syslinux GPTMBR data on each disk device
      ansible.builtin.command:
        cmd: "{{ chroot_cmd }} bash -c 'dd bs=440 count=1 conv=notrunc if=/usr/lib/syslinux/mbr/gptmbr.bin of={{ item }}'"
      register: cmd_output
      changed_when:
        cmd_output.rc == 0
      ignore_errors: true
      loop:
        "{{ disk_by_id }}"

    - name: Copy Logo Images and Icons
      ansible.builtin.copy:
        src: "files/{{ item.source }}"
        dest: "{{ live_cd_mountpoint }}/{{ item.dest }}"
        owner: "root"
        group: "root"
        mode: "0644"
      with_items:
        - { source: "logo_sm.jpg", dest: "{{ syslinx_path }}/" }
      when:
        - refind_boot_menu_logo  | default(false)
